In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
ls

Codebook.pdf*                    gtd1993_0617dist.xlsx*
Data Cleaning Notebook.ipynb     gtd_13to16_0617dist.xlsx*
GTDDistributionletter2017.pdf*   gtd_70to94_0617dist.xlsx*
TermsofUse.pdf*                  gtd_95to12_0617dist.xlsx*
globalterrorismdb_0617dist.xlsx*


In [3]:
data = pd.read_excel("globalterrorismdb_0617dist.xlsx")

In [4]:
data.shape

(170350, 135)

In [5]:
data.columns

Index(['eventid', 'iyear', 'imonth', 'iday', 'approxdate', 'extended',
       'resolution', 'country', 'country_txt', 'region',
       ...
       'addnotes', 'scite1', 'scite2', 'scite3', 'dbsource', 'INT_LOG',
       'INT_IDEO', 'INT_MISC', 'INT_ANY', 'related'],
      dtype='object', length=135)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170350 entries, 0 to 170349
Columns: 135 entries, eventid to related
dtypes: datetime64[ns](1), float64(53), int64(24), object(57)
memory usage: 175.5+ MB


In [7]:
data.isnull().sum()

eventid                    0
iyear                      0
imonth                     0
iday                       0
approxdate            162886
extended                   0
resolution            168131
country                    0
country_txt                0
region                     0
region_txt                 0
provstate              14502
city                     446
latitude                4606
longitude               4606
specificity                4
vicinity                   0
location              122376
summary                66138
crit1                      0
crit2                      0
crit3                      0
doubtterr                  0
alternative           143719
alternative_txt       143719
multiple                   0
success                    0
suicide                    0
attacktype1                0
attacktype1_txt            0
                       ...  
propextent            109805
propextent_txt        109805
propvalue             134863
propcomment   

In [8]:
non_null_cols = []

for col in data.columns:
    if data[col].isnull().sum() == 0:
        non_null_cols.append(col)

In [9]:
non_null_cols

['eventid',
 'iyear',
 'imonth',
 'iday',
 'extended',
 'country',
 'country_txt',
 'region',
 'region_txt',
 'vicinity',
 'crit1',
 'crit2',
 'crit3',
 'doubtterr',
 'multiple',
 'success',
 'suicide',
 'attacktype1',
 'attacktype1_txt',
 'targtype1',
 'targtype1_txt',
 'gname',
 'individual',
 'weaptype1',
 'weaptype1_txt',
 'property',
 'dbsource',
 'INT_LOG',
 'INT_IDEO',
 'INT_MISC',
 'INT_ANY']

In [10]:
len(non_null_cols)

31

Starting off 31 non nulls columns

In [11]:
cols_with_nulls = []

for col in data.columns:
    if col not in non_null_cols:
        cols_with_nulls.append(col)

In [12]:
data_nulls = data[cols_with_nulls].copy()

In [13]:
data_nulls.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170350 entries, 0 to 170349
Columns: 104 entries, approxdate to related
dtypes: datetime64[ns](1), float64(53), object(50)
memory usage: 135.2+ MB


In [14]:
data_nulls.columns

Index(['approxdate', 'resolution', 'provstate', 'city', 'latitude',
       'longitude', 'specificity', 'location', 'summary', 'alternative',
       ...
       'ransompaidus', 'ransomnote', 'hostkidoutcome', 'hostkidoutcome_txt',
       'nreleased', 'addnotes', 'scite1', 'scite2', 'scite3', 'related'],
      dtype='object', length=104)

In [15]:
cols_w_nulls_keep = data_nulls.isnull().sum().sort_values(ascending = False).iloc[-28:].index

In [16]:
data_nulls = data_nulls[cols_w_nulls_keep].copy()

In [17]:
data_nulls.head(1)

ransom  nperps  nperpcap  nwoundte  nkillter scite1 summary  claimed  \
0     0.0     NaN       NaN       NaN       NaN    NaN     NaN      NaN   

   nwoundus  nkillus     ...      targsubtype1_txt  longitude   latitude  \
0       NaN      NaN     ...        Named Civilian -69.951164  18.456792   

          natlty1_txt  natlty1       target1           city  guncertain1  \
0  Dominican Republic     58.0  Julio Guzman  Santo Domingo          0.0   

  ishostkid  specificity  
0       0.0          1.0  

[1 rows x 28 columns]

In [18]:
data_nulls.ransom.unique()

array([ 0.,  1., nan, -9.])

In [19]:
#Fill in nulls of ransom with -9

data_nulls.ransom.fillna(-9., inplace=True)

In [20]:
# data_nulls.nperps.value_counts(dropna=False)

In [21]:
data_nulls.nperps.fillna(-99.0, inplace=True)

In [22]:
data_nulls.nperpcap.unique()

array([  nan, -99. ,   1. ,   2. ,   0. ,   4. ,   3. ,   6. ,   5. ,
         7. ,   8. ,   9. ,  10. ,  26. ,  24. ,  13. ,  14. ,  45. ,
        12. ,  11. ,   2.5,  25. ,  32. ,  27. ,  -9. ,  15. ,  43. ,
        21. ,  50. , 406. ,  17. , 100. ,  60. ,  87. ,  55. ,  20. ,
        29. ,  76. ,  40. , 271. ,  28. ,  16. ,  19. ,  30. , 200. ,
        41. ,  18. , 126. ,  23. ,  22. ,  63. ])

In [23]:
data_nulls.nperpcap.fillna(-99., inplace=True)

In [24]:
data_nulls.nwoundte.unique()

array([ nan,   0.,   1.,   4.,   2.,   3.,   5.,   6.,  50.,  10.,  16.,
        20.,   9.,  13.,  11., 200.,   7.,  15.,  31.,   8.,  12.,  25.,
        30.,  38.,  14.,  21.,  24.,  18.,  62.,  17., 150.,  22.,  23.,
        33.,  19.,  40.,  51., 101.,  60.,  35.,  53.,  26., 100.])

In [25]:
data_nulls.drop("nwoundte", axis = 1, inplace=True)

In [26]:
data_nulls.drop("nkillter", axis = 1, inplace=True)

In [27]:
data_nulls.head(1)

ransom  nperps  nperpcap scite1 summary  claimed  nwoundus  nkillus  \
0     0.0   -99.0     -99.0    NaN     NaN      NaN       NaN      NaN   

  weapdetail corp1     ...      targsubtype1_txt  longitude   latitude  \
0        NaN   NaN     ...        Named Civilian -69.951164  18.456792   

          natlty1_txt  natlty1       target1           city  guncertain1  \
0  Dominican Republic     58.0  Julio Guzman  Santo Domingo          0.0   

   ishostkid specificity  
0        0.0         1.0  

[1 rows x 26 columns]

In [28]:
data_nulls.drop("scite1", axis = 1, inplace=True)

In [29]:
data_nulls.summary.isnull().sum()

66138

In [30]:
data_nulls.drop("summary", axis = 1, inplace=True)

In [31]:
data_nulls.claimed.unique()

array([nan,  0.,  1., -9.])

In [32]:
data_nulls.claimed.fillna(-9., inplace=True)

In [34]:
data_nulls.isnull().sum()

ransom                  0
nperps                  0
nperpcap                0
claimed                 0
nwoundus            64710
nkillus             64459
weapdetail          59385
corp1               42566
weapsubtype1        19426
weapsubtype1_txt    19426
nwound              15325
provstate           14502
nkill                9682
targsubtype1         9345
targsubtype1_txt     9345
longitude            4606
latitude             4606
natlty1_txt          1394
natlty1              1394
target1               636
city                  446
guncertain1           379
ishostkid             178
specificity             4
dtype: int64

In [35]:
data_nulls.shape

(170350, 24)

In [36]:
data_nulls.drop(["nwoundus", "nkillus"], axis = 1, inplace=True)

In [38]:
data_nulls.weapdetail.fillna("no description", inplace=True)

In [39]:
data_nulls.corp1.fillna("unknown", inplace=True)

In [40]:
data_nulls.weapsubtype1.fillna("unknown", inplace=True)

In [41]:
data_nulls.drop(["weapsubtype1_txt"], axis = 1, inplace=True)

In [43]:
data_nulls.index

RangeIndex(start=0, stop=170350, step=1)

In [44]:
data.shape

(170350, 135)

In [45]:
df = data[non_null_cols].copy()

In [46]:
df.shape

(170350, 31)

In [47]:
data_nulls.shape

(170350, 21)

In [48]:
df = pd.concat([df, data_nulls], axis = 1)

In [49]:
df.isnull().sum()

eventid                 0
iyear                   0
imonth                  0
iday                    0
extended                0
country                 0
country_txt             0
region                  0
region_txt              0
vicinity                0
crit1                   0
crit2                   0
crit3                   0
doubtterr               0
multiple                0
success                 0
suicide                 0
attacktype1             0
attacktype1_txt         0
targtype1               0
targtype1_txt           0
gname                   0
individual              0
weaptype1               0
weaptype1_txt           0
property                0
dbsource                0
INT_LOG                 0
INT_IDEO                0
INT_MISC                0
INT_ANY                 0
ransom                  0
nperps                  0
nperpcap                0
claimed                 0
weapdetail              0
corp1                   0
weapsubtype1            0
nwound      

In [50]:
df.dropna(inplace=True)

Excess columns and nulls have been removed. Outputting data as a csv file.

In [51]:
df.to_csv("clean_data.csv")